DEFAULT_CONCURRENT_LIMIT = 10
HF_EXACT_NO_REPO_RECHECK_DAYS = 7
ARXIV_RELATION_NO_ARXIV_RECHECK_DAYS = 30
REPO_CACHE_DB_PATH = "cache.db"
CONTENT_CACHE_DIR = "cache"
OVERVIEW_CACHE_SUBDIR = "overview"
ABS_CACHE_SUBDIR = "abs"
ALPHAXIV_OVERVIEW_LANGUAGE = "en"
